export default Object.freeze({
    AUTH: '/auth',
    MENU: '/menu',
    MENU_ITEM: '/menu/:id',
    NEW_MENU_ITEM: '/add',
    ORDER_HISTORY: '/order-history',
    CART: '/cart',
    CHECKOUT: '/checkout',
    ACCOUNT: '/account',
    PLANNER: '/planner',
    ABOUT: '/about',
    CONTACT: '/contact',
    DELIVERY: '/delivery',
    FAVOURITES: '/favourites',
  });